apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveclinic-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveclinic-backend
  template:
    metadata:
      labels:
        app: liveclinic-backend
    spec:
      containers:
        - name: backend
          image: jonahirande/live-clinic-backend:1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: liveclinic-db
            - name: DB_PORT
              value: "5432"

