apiVersion: v1
kind: Service
metadata:
  namespace: liveclinic
  name: liveclinic-db
  labels:
    app: liveclinic-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: liveclinic-db
