apiVersion: v1
kind: Service
metadata:
  namespace: liveclinic
  name: liveclinic-frontend
  labels:
    app: liveclinic-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: liveclinic-frontend
