apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: liveclinic
  name: liveclinic-frontend
spec:
  to:
    kind: Service
    name: liveclinic-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
