apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveclinic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveclinic-frontend
  template:
    metadata:
      labels:
        app: liveclinic-frontend
    spec:
      containers:
        - name: frontend
          image: jonahirande/live-clinic-frontend:1.0
          ports:
            - containerPort: 3000
